name: Full CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Move to project directory
        run: cd project && ls -lhtr && pwd

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Save image
        run: docker save myapp > myapp.tar

      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: myapp.tar

  deploy:
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load image
        run: docker load < myapp.tar

      - name: Run container
        run: docker run -d myapp
