name: Deploy after CI

on:
  workflow_run:
    workflows: ["CI on Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying after CI success"
