name: Secrets & Environment Demo

on:
  workflow_dispatch:

jobs:

  # 🔹 Repo-level
  repo-level:
    runs-on: self-hosted

    steps:
      - name: Show Repository Variables
        run: |
          echo "Repo ENV: $REPO_ENV"
          echo "Repo SECRET: $REPO_PASS"
        env:
          REPO_ENV: ${{ vars.REPO_ENV }}
          REPO_PASS: ${{ secrets.REPO_PASS }}

  # 🔹 DEV environment
  dev-environment:
    runs-on: self-hosted
    environment: dev

    steps:
      - name: Show DEV Variables
        run: |
          echo "DEV ENV: $DEV_ENV"
          echo "DEV SECRET: $DEV_PASS"
        env:
          DEV_ENV: ${{ vars.DEV_ENV }}
          DEV_PASS: ${{ secrets.DEV_PASS }}

      - name: Show Repo Variables in DEV
        run: |
          echo "Repo ENV: $REPO_ENV"
          echo "Repo SECRET: $REPO_PASS"
        env:
          REPO_ENV: ${{ vars.REPO_ENV }}
          REPO_PASS: ${{ secrets.REPO_PASS }}

  # 🔹 PROD environment
  prod-environment:
    runs-on: self-hosted
    environment: prod

    steps:
      - name: Show PROD Variables
        run: |
          echo "PROD ENV: $PROD_ENV"
          echo "PROD SECRET: $PROD_PASS"
        env:
          PROD_ENV: ${{ vars.PROD_ENV }}
          PROD_PASS: ${{ secrets.PROD_PASS }}

      - name: Show Repo Variables in PROD
        run: |
          echo "Repo ENV: $REPO_ENV"
          echo "Repo SECRET: $REPO_PASS"
        env:
          REPO_ENV: ${{ vars.REPO_ENV }}
          REPO_PASS: ${{ secrets.REPO_PASS }}
