name: Secrets & Environment Demo

on:
  workflow_dispatch:

jobs:

  # 🔹 Job 1: Using Repository-level env & secrets
  repo-level:
    runs-on: devops-practice

    steps:
      - name: Show Repository Variables
        run: |
          echo "Repo ENV: $REPO_ENV"
          echo "Repo SECRET: $REPO_PASS"

  # 🔹 Job 2: Using DEV Environment
  dev-environment:
    runs-on: devops-practice
    environment: dev

    steps:
      - name: Show DEV Variables
        run: |
          echo "DEV ENV: $DEV_ENV"
          echo "DEV SECRET: $DEV_PASS"

      - name: Show Repo still accessible
        run: |
          echo "Repo ENV: $REPO_ENV"
          echo "Repo SECRET: $REPO_PASS"

  # 🔹 Job 3: Using PROD Environment
  prod-environment:
    runs-on: devops-practice
    environment: prod

    steps:
      - name: Show PROD Variables
        run: |
          echo "PROD ENV: $PROD_ENV"
          echo "PROD SECRET: $PROD_PASS"

      - name: Show Repo still accessible
        run: |
          echo "Repo ENV: $REPO_ENV"
          echo "Repo SECRET: $REPO_PASS"
